---
stages:
  - deploy

variables:
  FLATPAK_MANIFEST: dist/com.ldjam.ananace.LD43.yml
  GIT_SUBMODULE_STRATEGY: normal

.flatpak_cache:
  cache:
    key: "flatpak"
    paths:
      - .flatpak-builder/cache/

build_flatpak:
  extends: .flatpak_cache
  stage: deploy
  image: ananace/flatpak-builder
  script:
    - flatpak install --no-related --assumeyes flathub org.freedesktop.Sdk//18.08
    - flatpak-builder --force-clean --repo=export app ${FLATPAK_MANIFEST}
    - flatpak build-bundle export/ com.ldjam.ananace.LD43.flatpak com.ldjam.ananace.LD43
  when: manual
  artifacts:
    paths:
      - com.ldjam.ananace.LD43.flatpak
    expire_in: 1 week
